import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import "../styles/styles.scss"

import { getSiteSettings } from "./queries/getSiteSettings";
import { generateMetadata as genMeta } from "./queries/generateMetaData";

export async function generateMetaData() {
  const settings = await getSiteSettings();

  return genMeta({
    siteName: settings?.siteName,
    siteUrl: settings?.siteUrl,
    defaultSeo: settings?.defaultSeo,
  });
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
